mongodb:
  hostname: mongo
  image: mongo:3.2.6
  container_name: mongodb
mongo-seed:
  image: mongo:3.2.6
  links:
    - mongodb:mongodb
  volumes:
    - ./data/dumps:/tmp/data
  command:
    'bash -c "mongoimport --host mongodb --db measures --collection measure /tmp/data/data.json"'    
spark_toree:
  build: spark_toree
  dockerfile: Dockerfile
  container_name: spark_toree
  volumes: 
    - ./data:/tmp/data
  ports:
    - 8889:8889
spark_web:
  build: spark_web
  dockerfile: Dockerfile
  container_name: spark_web
  volumes:
    - ./data:/tmp/data
  ports:
    - 5006:5006
  links:
    - master
    - mongodb:mongodb
master:
  #image: gettyimages/spark
  build: spark_master
  dockerfile: Dockerfile
  command: bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  container_name: spark_master
  environment:
    MASTER: spark://master:7077
    SPARK_CONF_DIR: /conf
    SPARK_PUBLIC_DNS: localhost
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
    - 8888:8888
  volumes:
    - ./conf/master:/conf
    - ./data:/tmp/data
  links:
    - mongodb:mongodb
proxy:
  image: lerenn/nginx-reverse-proxy  
  container_name: proxy
  hostname: proxy
  mem_limit: 50m
  ports:
    - 1080:80
  volumes:
    - /home/francesco/docker-spark/data/proxy:/etc/nginx/sites-available
worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_PORT: 8881
    SPARK_PUBLIC_DNS: localhost
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - master
    - spark_web
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
    - 8081
  volumes:
    - ./conf/worker:/conf
    - ./data:/tmp/data
