version: "2.0"

services:
  spark_toree:
    build: ./spark_toree
    command: jupyter notebook  --allow-root --ip=0.0.0.0 --port=8888 --notebook-dir=/tmp/data
    container_name: spark_toree
    volumes:
      - ./data:/tmp/data
    ports:
      - 2889:8888
  master:
    image: gettyimages/spark
    #command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    container_name: spark_master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 2040:4040
      - 2066:6066
      - 2077:7077
      - 2080:8080
      - 2888:8888
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data
  worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_PORT: 8881
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_WEBUI_PORT: 8081
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data
